export const popularSearchTerms = [
    "Mars Rover", "Curiosity Rover", "Perseverance Rover", "Opportunity Rover", "Spirit Rover",
    "Mars Surface", "Mars Craters", "Olympus Mons", "Valles Marineris", "Phobos", "Deimos",
    "Jupiter", "Great Red Spot", "Europa", "Ganymede", "Callisto", "Io", "Jupiter Moons",
    "Saturn", "Rings of Saturn", "Titan", "Enceladus", "Mimas", "Dione", "Tethys", "Rhea",
    "Uranus", "Neptune", "Triton", "Pluto", "Ceres", "Asteroid Belt", "Kuiper Belt", "Oort Cloud",
    "Andromeda Galaxy", "Milky Way Galaxy", "Triangulum Galaxy", "Sombrero Galaxy", "Whirlpool Galaxy",
    "Orion Nebula", "Helix Nebula", "Crab Nebula", "Carina Nebula", "Eagle Nebula", "Horsehead Nebula",
    "Pillars of Creation", "Rosette Nebula", "Lagoon Nebula", "Ring Nebula",
    "Hubble Telescope", "James Webb Telescope", "Spitzer Space Telescope", "Chandra X-ray Observatory",
    "International Space Station", "Space Shuttle", "SpaceX", "Falcon 9", "Falcon Heavy", "Starship",
    "Blue Origin", "New Shepard", "Virgin Galactic", "Apollo Mission", "Apollo 11", "Buzz Aldrin",
    "Neil Armstrong", "Moon Landing", "Lunar Module", "Saturn V", "Artemis Program", "Lunar Gateway",
    "Supernova", "Black Hole", "Event Horizon", "Wormhole", "Quasar", "Pulsar", "Neutron Star",
    "Solar Flare", "Coronal Mass Ejection", "Sunspots", "Solar Eclipse", "Lunar Eclipse",
    "Earth from Space", "Blue Marble", "Aurora Borealis", "Aurora Australis", "Planet Earth",
    "Exoplanet", "Kepler Space Telescope", "TESS", "Habitable Zone", "Goldilocks Zone",
    "Space Probe", "Voyager 1", "Voyager 2", "Pioneer 10", "Pioneer 11", "New Horizons",
    "Meteor Shower", "Perseids", "Leonids", "Geminids", "Comet Halley", "Comet NEOWISE",
    "Asteroid Impact", "Near-Earth Object", "Chicxulub Crater",
    "Rocket Launch", "Space Suit", "Zero Gravity", "Microgravity", "Cosmic Microwave Background",
    "Dark Matter", "Dark Energy", "Big Bang", "Cosmology", "Space Colonization",
    "Terraforming Mars", "Astrobiology", "SETI", "Radio Telescope", "Infrared Telescope",
    "Gamma Ray Burst", "X-Ray Astronomy", "Interstellar Space", "Solar System", "Planetary Rings",
    "Space Images", "Hubble Images", "James Webb Images",
    "Infrared Space Images",
    "Ultraviolet Space Images",
    "Deep Space Images",
    "High-Resolution Space Images",
    "Astronomy Images",
    "Galaxy Images",
    "Planetary Images",
    "Nebula Images",
    "Exoplanet Images",
    "Earth Observation Images",
    "Lunar Images",
    "Mars Surface Images",
    "Jupiter Images",
    "Saturn Images",
    "Venus Images",
    "Mercury Images",
    "Asteroid Images",
    "Comet Images",
    "Solar Images",
    "Sunspot Images",
    "Aurora Images",
    "Milky Way Images",
    "Black Hole Images",
    "Supernova Remnant Images",
    "Cosmic Microwave Background Images",
    "Star Cluster Images",
    "Space Photography",
    "NASA Image Gallery",
    "Hubble Space Telescope Photos",
    "James Webb Space Telescope Photos"
];
